project:
  name: Zuss
  version: 1.0.0
  description: A React application with login functionality.
dependencies:
  react: ^17.0.2
  react-dom: ^17.0.2
  react-scripts: 4.0.3
  react-testing-library: ^11.2.6
  jest: ^26.6.3
scripts:
  start: react-scripts start
  build: react-scripts build
  test: react-scripts test
  eject: react-scripts eject
components:
  - App
  - Login
styles:
  - App.css
tests:
  - App.test.js
