name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Change working directory to 'backend' for npm install
      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      # Change working directory to 'backend' for npm test
      - name: Run tests
        run: npm test
        working-directory: ./backend
      
      - name: Build
        run: npm run build --if-present
        working-directory: ./backend